-- AUTO GENERATED

CREATE TABLE IF NOT EXISTS achievements (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE achievements ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS admin_activity_logs (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE admin_activity_logs ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS admin_logs (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE admin_logs ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS admin_permissions (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE admin_permissions ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS admin_roles (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE admin_roles ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS ads (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE ads ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS advertisement_analytics (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE advertisement_analytics ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS advertisements (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE advertisements ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS ai_ad_reviews (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE ai_ad_reviews ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS ai_course_reviews (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE ai_course_reviews ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS ai_product_reviews (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE ai_product_reviews ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS applications (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE applications ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS badges (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE badges ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_analytics (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_analytics ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_deal_requests (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_deal_requests ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_inquiries (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_inquiries ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_interest_requests (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_interest_requests ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_inventory (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_inventory ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_needs (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_needs ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_offers (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_offers ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_opportunities (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_opportunities ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_orders (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_orders ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_payments (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_payments ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_products (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_products ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_profiles (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_profiles ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_reports (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_reports ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_reviews (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_reviews ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_sale_inquiries (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_sale_inquiries ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_sale_listings (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_sale_listings ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_sales (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_sales ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_subscriptions (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_subscriptions ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS business_verification_requests (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE business_verification_requests ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS businesses (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE businesses ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS career_profiles (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE career_profiles ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS certificates (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE certificates ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS company_administrators (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE company_administrators ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS company_assets (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE company_assets ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS company_employees (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE company_employees ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS company_financial_records (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE company_financial_records ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS company_investors (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE company_investors ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS company_profiles (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE company_profiles ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS course_catalog (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE course_catalog ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS course_categories (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE course_categories ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS course_enrollments (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE course_enrollments ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS course_publish_logs (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE course_publish_logs ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS course_reviews (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE course_reviews ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS course_submissions (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE course_submissions ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS courses (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE courses ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS deal_ai_summaries (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE deal_ai_summaries ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS deal_contracts (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE deal_contracts ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS deal_meeting_requests (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE deal_meeting_requests ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS deal_messages (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE deal_messages ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS deal_negotiations (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE deal_negotiations ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS deal_payments (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE deal_payments ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS deal_proposals (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE deal_proposals ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS deal_rooms (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE deal_rooms ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS earning_tasks (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE earning_tasks ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS enrollments (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS entity_verifications (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE entity_verifications ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS feedback (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS holding_companies (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE holding_companies ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS instructor_applications (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE instructor_applications ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS instructor_courses (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE instructor_courses ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS instructor_feedback (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE instructor_feedback ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS instructors (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE instructors ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS job_applications (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE job_applications ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS job_opportunities (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE job_opportunities ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS jobs (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS learner_badges (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE learner_badges ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS learner_profiles (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE learner_profiles ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS learner_skills (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE learner_skills ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS learner_stats (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE learner_stats ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS lesson_bookmarks (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE lesson_bookmarks ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS lesson_progress (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE lesson_progress ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS meeting_requests (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE meeting_requests ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS onboarding_progress (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE onboarding_progress ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS opportunities (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE opportunities ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS opportunity_matches (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE opportunity_matches ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS payment_transactions (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE payment_transactions ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS profile_details (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE profile_details ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS profiles (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS quiz_results (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE quiz_results ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS referral_codes (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE referral_codes ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS referrals (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS reviews (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS student_notes (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE student_notes ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS task_applications (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE task_applications ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS task_matches (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE task_matches ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS task_progress (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE task_progress ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS user_badges (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE user_badges ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS user_profiles (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS user_progress (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE user_progress ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS user_roles (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS user_verification_requests (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE user_verification_requests ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS learner_kyc (
 id BIGSERIAL PRIMARY KEY,
 user_id UUID,
 display_name TEXT,
 legal_name TEXT,
 dob DATE,
 phone TEXT,
 email TEXT,
 country TEXT,
 id_document_url TEXT,
 verification_status TEXT DEFAULT 'pending',
 created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS business_verification (
 id BIGSERIAL PRIMARY KEY,
 business_name TEXT,
 owner_name TEXT,
 registration_number TEXT,
 official_email TEXT,
 address TEXT,
 phone TEXT,
 document_url TEXT,
 verification_status TEXT DEFAULT 'pending',
 created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS investor_verification (
 id BIGSERIAL PRIMARY KEY,
 investor_name TEXT,
 investment_focus TEXT,
 country TEXT,
 proof_of_funds_url TEXT,
 id_document_url TEXT,
 verification_status TEXT DEFAULT 'pending',
 created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS company_due_diligence (
 id BIGSERIAL PRIMARY KEY,
 company_name TEXT,
 industry TEXT,
 ownership_documents TEXT,
 financial_documents TEXT,
 compliance_documents TEXT,
 status TEXT DEFAULT 'pending',
 created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS government_requests (
 id BIGSERIAL PRIMARY KEY,
 department TEXT,
 officer_name TEXT,
 officer_id TEXT,
 official_email TEXT,
 request_type TEXT,
 legal_basis TEXT,
 case_reference TEXT,
 court_order_url TEXT,
 status TEXT DEFAULT 'pending',
 created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_logs (
 id BIGSERIAL PRIMARY KEY,
 actor_id UUID,
 action TEXT,
 target_type TEXT,
 target_id TEXT,
 ip_address TEXT,
 user_agent TEXT,
 created_at TIMESTAMPTZ DEFAULT NOW()
);

