const {createClient}=require('@supabase/supabase-js');
function db(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_KEY;if(!url||!key)throw new Error('Supabase server configuration is missing.');return createClient(url,key)}
function ref(p){return `${p}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`}
function token(req){const h=req.headers?.authorization||req.headers?.Authorization||'';return h.startsWith('Bearer ')?h.slice(7):''}
async function user(req){const t=token(req);if(!t)return null;const {data,error}=await db().auth.getUser(t);return error?null:data?.user||null}
async function listSuppliers({limit=30}={}){const n=Math.min(Math.max(Number(limit)||30,1),100);const {data,error}=await db().from('businesses').select('id,reference_id,business_name,legal_name,business_type,category,subcategory,description,website,country,city,address,contact_person_name,contact_role,contact_email,contact_phone,contact_whatsapp').eq('status','active').eq('visibility','public').eq('verification_status','approved').order('created_at',{ascending:false}).limit(n);if(error)throw error;return data||[]}
async function createRequest(req,p){const u=await user(req);if(!u)throw Object.assign(new Error('Sign in is required to create a sourcing request.'),{status:401});const product=String(p.product_service||'').trim(),location=String(p.delivery_location||'').trim(),quantity=Number(p.quantity||1);if(!product||!location||!Number.isFinite(quantity)||quantity<=0)throw Object.assign(new Error('Product/service, quantity and delivery location are required.'),{status:400});const row={reference_id:ref('LEH-SRC'),customer_id:u.id,product_service:product,quantity,specifications:p.specifications||null,delivery_location:location,needed_by:p.needed_by||null,budget:p.budget===''||p.budget==null?null:Number(p.budget),budget_currency:p.budget_currency||'PKR',condition:p.condition||'New',customer_name:p.customer_name||u.user_metadata?.full_name||null,customer_email:p.customer_email||u.email||null,customer_phone:p.customer_phone||null,customer_whatsapp:p.customer_whatsapp||null,status:'open'};const {data,error}=await db().from('sourcing_requests').insert(row).select('*').single();if(error)throw error;return data}
async function listMyRequests(req){const u=await user(req);if(!u)throw Object.assign(new Error('Sign in is required.'),{status:401});const {data,error}=await db().from('sourcing_requests').select('*,sourcing_quotations(*)').eq('customer_id',u.id).order('created_at',{ascending:false}).limit(100);if(error)throw error;return data||[]}
async function createQuote(req,p){const u=await user(req);if(!u)throw Object.assign(new Error('Sign in is required to submit a quotation.'),{status:401});const requestId=String(p.request_id||''),businessId=String(p.supplier_business_id||''),unit=Number(p.unit_price);if(!requestId||!businessId||!Number.isFinite(unit)||unit<0)throw Object.assign(new Error('Request, supplier business and valid unit price are required.'),{status:400});const c=db();const {data:b,error:be}=await c.from('businesses').select('id,owner_id,contact_person_name,contact_email,contact_phone,contact_whatsapp').eq('id',businessId).single();if(be||!b||b.owner_id!==u.id)throw Object.assign(new Error('You can only quote as the owner of the supplier business.'),{status:403});const {data:r,error:re}=await c.from('sourcing_requests').select('id,quantity,status').eq('id',requestId).single();if(re||!r||r.status!=='open')throw Object.assign(new Error('Sourcing request is not available for quotation.'),{status:404});const row={reference_id:ref('LEH-QTE'),request_id:requestId,supplier_business_id:businessId,supplier_contact_name:p.supplier_contact_name||b.contact_person_name||null,supplier_contact_email:p.supplier_contact_email||b.contact_email||null,supplier_contact_phone:p.supplier_contact_phone||b.contact_phone||null,supplier_contact_whatsapp:p.supplier_contact_whatsapp||b.contact_whatsapp||null,unit_price:unit,quantity:Number(p.quantity||r.quantity||1),delivery_cost:Number(p.delivery_cost||0),currency:p.currency||'PKR',estimated_delivery_days:p.estimated_delivery_days===''||p.estimated_delivery_days==null?null:Number(p.estimated_delivery_days),valid_until:p.valid_until||null,terms:p.terms||null,status:'submitted'};const {data,error}=await c.from('sourcing_quotations').insert(row).select('*').single();if(error)throw error;return data}
module.exports={listSuppliers,createRequest,listMyRequests,createQuote};
